package my.azimovua.item;

import eu.pb4.polymer.core.api.item.PolymerItem;
import eu.pb4.polymer.resourcepack.api.PolymerResourcePackUtils;
import my.azimovua.TestPolymere;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.item.tooltip.TooltipType;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.Nullable;

import java.util.List;

// To create new item, you need to extend vanilla Item and implement PolymerItem interface
// Item name can be changed in resources/assets/{MOD_ID}/lang/{language_code}.json (AzimovUA)
public class ExamplePolymerItem extends Item implements PolymerItem {

    public ExamplePolymerItem(Settings settings) {
        super(settings);
    }

    @Override
    public void appendTooltip(ItemStack itemStack, @Nullable Item.TooltipContext context, List<Text> tooltip, TooltipType type) {
        tooltip.add(Text.of("This is a polymer item!"));
    }

    @Override
    public Item getPolymerItem(ItemStack itemStack, @Nullable ServerPlayerEntity player) {
        // Client-side item that will be shown
        // Items.DIAMOND can be declared as a constant in the class
        // Something like "base item", but I'm lazy (AzimovUA)
        return Items.DIAMOND;
    }

    @Override
    public int getPolymerCustomModelData(ItemStack itemStack, @Nullable ServerPlayerEntity player) {
        /* this method is used by Polymer to change item NBT CustomModelData (CMD),
        so resourcepacks can use it. CMD number is generated by Polymer, and
        I don't know how to hard-set it, but it doesn't matter since Polymer creates resourcepack for you.
        In recources/assets/{MOD_ID}/models/item/ you should have .json file that points to a .png-texture (AzimovUA) */

        return PolymerResourcePackUtils.requestModel(Items.DIAMOND, Identifier.of(TestPolymere.MOD_ID, "item/polymer_item")).value();
    }
}
